name: CI for All Projects

on:
  push:
    branches: [ master ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & Build Frontend
        working-directory: code-platform/code-platform
        run: |
          npm install
          npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & Test Backend
        working-directory: code-platform/backend
        run: |
          npm install
          npm test

  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & Test Compiler
        working-directory: code-platform/compiler-server
        run: |
          npm install
          npm test
